#!/usr/bin/env python3
"""Generate a SolaraViz app.py for a Mesa model and experiment config."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shlex
import textwrap


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, help="Path to a Python file defining the Mesa model class.")
    parser.add_argument("--config", required=True, help="Path to a JSON experiment config.")
    parser.add_argument("--output-app", required=True, help="Path where the generated Solara app.py should be written.")
    parser.add_argument("--title", help="Title shown in the SolaraViz page.")
    return parser.parse_args()


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def first_parameter_values(parameters: dict) -> dict:
    selected = {}
    for key, value in parameters.items():
        if isinstance(value, list):
            if not value:
                raise SystemExit(f"Parameter {key!r} has an empty sweep list")
            selected[key] = value[0]
        else:
            selected[key] = value
    return selected


def write_app(model_path: Path, config: dict, output_app: Path, title: str) -> None:
    for required in ["model_class", "parameters"]:
        if required not in config:
            raise SystemExit(f"Config missing required field: {required}")

    model_class = config["model_class"]
    model_params = first_parameter_values(config.get("parameters", {}))
    seed_values = config.get("seeds") or [None]
    if seed_values[0] is not None:
        model_params["seed"] = seed_values[0]

    app = f'''\
    """SolaraViz app generated by the abm-modeling skill."""

    from __future__ import annotations

    import importlib.util
    from pathlib import Path
    import sys

    from mesa.visualization import SolaraViz, make_space_component
    from mesa.visualization.components import AgentPortrayalStyle


    MODEL_PATH = Path({str(model_path)!r})
    MODEL_CLASS_NAME = {model_class!r}


    def load_model_class():
        spec = importlib.util.spec_from_file_location("abm_visual_model", MODEL_PATH)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Cannot load model module from {{MODEL_PATH}}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        sys.path.insert(0, str(MODEL_PATH.parent))
        try:
            spec.loader.exec_module(module)
        finally:
            try:
                sys.path.remove(str(MODEL_PATH.parent))
            except ValueError:
                pass
        return getattr(module, MODEL_CLASS_NAME)


    def agent_portrayal(agent):
        condition = getattr(agent, "condition", None)
        colors = {{
            "fine": "tab:green",
            "burning": "tab:red",
            "burned": "tab:gray",
        }}
        return AgentPortrayalStyle(
            color=colors.get(condition, "tab:blue"),
            marker="s",
            size=80,
        )


    ModelClass = load_model_class()
    model_params = {model_params!r}
    model = ModelClass(**model_params)

    Space = make_space_component(agent_portrayal)
    page = SolaraViz(model, components=[Space], name={title!r})
    '''
    output_app.parent.mkdir(parents=True, exist_ok=True)
    output_app.write_text(textwrap.dedent(app), encoding="utf-8")


def main() -> int:
    args = parse_args()
    model_path = Path(args.model).resolve()
    config_path = Path(args.config).resolve()
    output_app = Path(args.output_app).resolve()
    config = load_json(config_path)
    title = args.title or config.get("experiment_name") or f"{config.get('model_class', 'Mesa')} Visualization"
    write_app(model_path, config, output_app, title)
    print(
        json.dumps(
            {
                "app": str(output_app),
                "run": f"solara run {shlex.quote(str(output_app))} --host 127.0.0.1 --port 8765",
                "run_args": ["solara", "run", str(output_app), "--host", "127.0.0.1", "--port", "8765"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
